common: &common
  dev_key: AI39si56zXaYYeIhrMack13lKTHuj95sOqfSHWkB2ASgI-XMH0PhI2hyl36vhS5zD2s85MkFhUBSObuNzeRBWfJn4ovqlqg5WA
  username: TNEWebcast
  password: Oliver2013

test:
  <<: *common
development:
  <<: *common
production:
  <<: *common